### ISSUE TITLE
Update to version 1.3.35 causes extension to stop working

### ISSUE THREAD

**Issue by dev64bit** [madskristensen/WebAccessibilityChecker#11]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.3.35

### Description
Latest update caused _Web Accessibility Checker_ to stop working.
I checked to ensure that the extension was enabled in Visual Studio.
I checked the Visual Studio extensions folder in Windows Explorer and noticed multiple folders containing identical copies of the updated version 1.3.35 files.
I uninstalled the extension from Visual Studio, removed the multiple copies from the Visual Studio extensions folder, and restarted Visual Studio.
I performed a fresh install of version 1.3.35 and restarted Visual Studio again.
The extension still did not function.

I removed the extension, restarted VS, and re-installed the old version.
Because I no longer had the old VSIX installer for version 1.3.33, I had to get a copy of the files from a co-worker to re-install the old version.
I manually copied the files to a new folder in the Visual Studio extensions folder, restarted Visual Studio, and then had to enable the extension because manually added extensions are not enabled to begin with.
The 1.3.33 version of the extension then functioned as expected. 

It would be nice if old VSIX installer versions could be made available for situations like this.

### Steps to recreate
1. Upgrade from 1.3.33 to 1.3.35
2. Begin Debugging in Visual Studio 
3. Check _Web Accessibility Checker_ sub menu in Browser Link dropdown menu

### Current behavior
Upgraded from version 1.3.33 to 1.3.35 today.
Extension no longer reports any errors in Visual Studio while debugging.
Run Now in All Browsers menu is disabled.
Tested with Internet Explorer 11 and Google Chrome 53.0.2785.116 (I don't currently have access to a more recent version of Chrome).

### Expected behavior
Web Accessibility Errors should be reported in Visual Studio while debugging.
Run Now in All Browsers menu should be enabled.

**Comment by cawerkenthin** [comment]
I have the same issue.  Worked prior to 1.3.35, now the Run Now in All Browsers menu is disabled and no messages display when Run on Page Load is checked.  Tested in IE 11.0.9600.18426, Chrome 54.0.2840.99 and 50.0.2.  Using VS Enterprise 2015, version 14.0.25425.01 Update 3.

**Comment by madskristensen** [comment]
Version 1.3.37 was just released. It should fix this issue

**Comment by dev64bit** [comment]
Confirmed that v 1.3.37 fixed the problem.
Thanks.
