### ISSUE TITLE
An unhandled Microsoft .Net Framework exceptiom occurred in the VSIXInstaller.exe [12004].

### ISSUE THREAD

**Issue by Mattacks** [madskristensen/WebAccessibilityChecker#12]
### Installed product versions
- Visual Studio: [2015 Enterprise] Extension already reported as being installed
- Visual Studio: [2017 Enterprise] Extension
- This extension: [example 1.3.37 ]

### Description
Crash as in Issue title when trying to install

### What I did [repeatable - twice]
Download and run the VSIX
It told me to exit apps, which I did (including VS2015 and 2017).
I pressed [End tasks] to kill the two remaining MSBuilds and something else

Got the above crash

### Workaround
From task manager kill the MsBuild tasks first: no crash

**Comment by madskristensen** [comment]
Fixed
