### ISSUE TITLE
While debugging pages scroll to the bottom.

### ISSUE THREAD

**Issue by CrashedMatrix** [madskristensen/WebAccessibilityChecker#14]
### Installed product versions
- Visual Studio 2015 Enterprise & Visual Studio 2017 Enterprise
- This extension:  1.4.46

### Description
While debugging ASP MVC C# web application in Visual Studio with the Web Accessibility Checker enabled, the page will scroll to the bottom once the page has fully loaded.

### Steps to recreate
1. Enable Web Accessibility Checker 
2. Debug a Web application in Visual Studio

### Current behavior
Recent updates in the last week seem to have caused this issue.

### Expected behavior
Before recent updates this extension did not cause this issue.

**Comment by madskristensen** [comment]
This was just fixed with release 1.4.47
