### ISSUE TITLE
Running the checker messes up my page's layout and javascript

### ISSUE THREAD

**Issue by csrakowski** [madskristensen/WebAccessibilityChecker#2]
### Installed product versions
- Visual Studio: [2015 Enterprise, update 2]
- This extension: [1.0.20]
### Description

We have an older Web Forms project and I was trying out the checker there.
When running the checker, my page's layout gets all messed up and some of the javascript broke. (All in browser, the development environment is left untouched)

Is this 'a known issue', 'expected behavior', or something else?
If it is expected behavior, I would be totally fine with that as long as there is a small warning that says so :-)
If you think it looks like this could be a bug, would it be one in the extension or in axe-core itself?
### Steps to recreate
1. Run check (either automatically on page load, or manually at a later time)
### Current behavior

It messes up my page's layout and javascript
### Expected behavior

Unsure

PS: As an aside, the axe-core project has a page where project's using it can add themselves to a list. 
Perhaps you already knew about it, but if not: here is the [link](https://github.com/dequelabs/axe-core/blob/master/doc/projects.md)

**Comment by madskristensen** [comment]
Thanks for the bug report. I expect it would be the axe-core javascript library that messes with your page. What browser do you use and does the issue reproduces in modern browsers such as Edge or Chrome?

**Comment by csrakowski** [comment]
I get the error in both Chrome and Edge (latest stable releases).
From your reply, I take it this isn't 'expected behavior' :-)
I will dig into axe-core a bit more, and file an issue with them if I pinpointed the cause.

Will keep you posted.

**Comment by madskristensen** [comment]
Very strange. I just pushed out an update that disable the auto-scrolling behavior

**Comment by csrakowski** [comment]
I updated the extension to 1.0.21 today and the issue is now fixed! :-)
Thanks for the quick fix!
